services:
  temporal:
    image: temporalio/auto-setup:1.25.2 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB: postgres12 
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PWD: 11234567
      POSTGRES_SEEDS: host.docker.internal
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
    ports:
      - "7233:7233"
    volumes:
      - ./temporal/dynamicConfig:/etc/temporal/config/dynamicconfig

  temporal-ui:
    image: temporalio/ui:2.31.2 
    depends_on:
      - temporal 
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000,http://localhost:5173
    ports:
      - "8080:8080"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # web interface